ingenic_fb_stage-y := ingenicfb.o\
			dpu_ctrl.o\
			hw_composer.o\
			hw_composer_fb.o\
			sysfs.o
obj-$(CONFIG_FB_INGENIC_STAGE_WIP) += ingenic_fb_stage.o

obj-$(CONFIG_HW_COMPOSER_V4L2_M2M) += hw_composer_v4l2.o

obj-$(CONFIG_ROT_INGENIC) += x2600_rotate.o
