ccflags-y := -I$(srctree)/module_drivers/drivers/dma/ingenic
ccflags-y += -I$(srctree)/drivers/dma

obj-y += multithread_test.o
obj-y += ddr_bandwidth_monitor.o
obj-y += ddr_change_freq.o
obj-y += l2c_test.o
obj-y += cpu_spinlock_test.o
obj-y += cpu_ccu_test.o
obj-y += raw_dma_test.o
obj-y += cpu_dma_test.o
obj-y += cpu_watch_test.o
obj-y += ddr_config.o
ccflags-y += -Wno-unused-function
