obj-y			+= core/
obj-y			+= common/

obj-$(CONFIG_SOC_X2000) += soc-x2000/
obj-$(CONFIG_SOC_M300) += soc-m300/
obj-$(CONFIG_SOC_X2100) += soc-x2000/
obj-$(CONFIG_SOC_X2600) += soc-x2600/
obj-$(CONFIG_SOC_AD100) += soc-ad100/
obj-$(CONFIG_SOC_X2500) += soc-x2500/
