## X2000 Supported Boards
snd_halley5_v20-y := halley5_v20.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY5_V20) += snd_halley5_v20.o
snd_gewu-y := gewu.o
obj-$(CONFIG_SND_ASOC_INGENIC_GEWU) += snd_gewu.o
snd_kale_v10-y := kale_v10.o
obj-$(CONFIG_SND_ASOC_INGENIC_KALE_V10) += snd_kale_v10.o
snd_zebra-y := zebra.o
obj-$(CONFIG_SND_ASOC_INGENIC_ZEBRA) += snd_zebra.o

## hippo Supported Boards
snd_hippo-board-y := hippo-board.o
obj-$(CONFIG_SND_ASOC_INGENIC_HIPPO_BOARD) += snd_hippo-board.o

## x1600 Supported Boards
snd_panda-y := panda.o
obj-$(CONFIG_SND_ASOC_INGENIC_PANDA) += snd_panda.o
snd_halley6-y := halley6.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY6) += snd_halley6.o
snd_x1600_iris-y := x1600_iris.o
obj-$(CONFIG_SND_ASOC_INGENIC_X1600_IRIS) += snd_x1600_iris.o

## x2660 Supported Boards
snd_x2660_halley-y := x2660_halley.o
obj-$(CONFIG_SND_ASOC_INGENIC_X2660_HALLEY) += snd_x2660_halley.o
snd_x2670_halley-y := x2660_halley.o
obj-$(CONFIG_SND_ASOC_INGENIC_X2670_HALLEY) += snd_x2670_halley.o
snd_x2600e_halley-y := x2660_halley.o
obj-$(CONFIG_SND_ASOC_INGENIC_X2600E_HALLEY) += snd_x2600e_halley.o
