ccflags-y := -I$(srctree)/module_drivers/drivers/dma/ingenic
ccflags-y += -I$(srctree)/drivers/dma
obj-$(CONFIG_INGENIC_CDBUS)     += ingenic_cdbus.o
obj-$(CONFIG_INGENIC_NEMC)     += ingenic_nemc.o
obj-$(CONFIG_INGENIC_PWM_AUDIO)     += ingenic_pwm_audio.o
obj-$(CONFIG_INGENIC_PWM_SMC)     += ingenic_pwm_smc.o
obj-$(CONFIG_INGENIC_HW_RANDOM)         += hw_random/ingenic-rng.o
